# Some basic Pytorch functions

### torch.Tensor

This is a short introduction about some basic functions commonly used with Pytorch tensors. The main reason why I've chosen these functions is because I usually use them when implementing deep learning models and I was confused about their proper use since some of them are quite similar, and even some times this has been the main reason why the model was not trained correctly:
- torch.permute vs torch.transpose
- torch.view vs torch.reshape and torch.contiguous
- torch.squeeze vs torch.unsqueeze
- torch.flatten
- torch.argmax 


In [2]:
import torch

## Function 1 - torch.permute vs torch.transpose

First, we create the tensor we'll be using in the assignment. 



In [3]:
x = torch.tensor([[[1, 2], [3, 4.],[5, 6]],[[7, 8],[9, 10],[11, 12]]])
x.dtype, x.size()

(torch.float32, torch.Size([2, 3, 2]))

**torch.transpose** is a function that changes the order of the dimensions in a tensor. For instance, if we want to swap the first for the last dimension, you can do the following: 

In [6]:
print(x)
y = x.transpose(0,2)
print(y, y.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])
tensor([[[ 1.,  7.],
         [ 3.,  9.],
         [ 5., 11.]],

        [[ 2.,  8.],
         [ 4., 10.],
         [ 6., 12.]]]) torch.Size([2, 3, 2])


And if you want to swap the three dimensions at the same time:

In [ ]:
y = x.transpose(1, 2, 0)
print(y, y.size())

TypeError: ignored

**torch.transpose** just swaps two dimensions, in this case you should use **torch.permute**. 

In [ ]:
y = x.permute(1, 2, 0)
print(y, y.size())

tensor([[[ 1.,  7.],
         [ 2.,  8.]],

        [[ 3.,  9.],
         [ 4., 10.]],

        [[ 5., 11.],
         [ 6., 12.]]]) torch.Size([3, 2, 2])


You can also swap just two dimensions using **torch.permute** as we did with **torch.transpose**, but you should specify all dimensions: 

In [7]:
y = x.permute(2,1,0)
print(y, y.size())

tensor([[[ 1.,  7.],
         [ 3.,  9.],
         [ 5., 11.]],

        [[ 2.,  8.],
         [ 4., 10.],
         [ 6., 12.]]]) torch.Size([2, 3, 2])


## Function 2 - torch.view vs torch.reshape

**torch.view** is a function that, by using the same data, changes the shape of the tensor. Here you have to specify the new size of each dimension. 

In [8]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [9]:
y = x.view(12)
print(y.size(), y)
z = y.view(3, 2, 2)
print(z.size(), z)

torch.Size([12]) tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])
torch.Size([3, 2, 2]) tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])


If you want to transpose and then change the size using view you can do the following: 

In [10]:
y = x.transpose(2,0)
print(y, y.size())
z = y.view(12)
print(z, z.size())

tensor([[[ 1.,  7.],
         [ 3.,  9.],
         [ 5., 11.]],

        [[ 2.,  8.],
         [ 4., 10.],
         [ 6., 12.]]]) torch.Size([2, 3, 2])


RuntimeError: ignored

This is not possible because by using transpose you loose the contiguity-like condition. You can solve this using **torch.reshape**, which does not depend on this condition, or by making the new tensor contiguous by using **torch.contiguous**. 

In [12]:
z1 = y.reshape(12)
print(z1, z1.size())
z2 = y.contiguous().view(12)
print(z2, z2.size())

tensor([ 1.,  7.,  3.,  9.,  5., 11.,  2.,  8.,  4., 10.,  6., 12.]) torch.Size([12])
tensor([ 1.,  7.,  3.,  9.,  5., 11.,  2.,  8.,  4., 10.,  6., 12.]) torch.Size([12])


## Function 3 - torch.flatten

This function is used to flatten a tensor. 

In [13]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [14]:
y = x.flatten()
print(y, y.size())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])


But if you want to flatten just one dimension, for instance the first one, you can do what is next:






In [15]:
y = x.flatten(end_dim=1)
print(y, y.size())

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])


In both cases you can use **torch.view** or **torch.reshape** for instance: 

In [16]:
y1 = x.view(-1)
print(y1, y1.size())

y2 = x.view(-1, 6, 2)
print(y2, y2.size())

y1 = x.reshape(-1)
print(y1, y1.size())

y2 = x.reshape(-1, 6, 2)
print(y2, y2.size())

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]) torch.Size([1, 6, 2])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]) torch.Size([12])
tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]) torch.Size([1, 6, 2])


## Function 4 - torch.squeeze vs torch.unsqueeze

If we decide to use **torch.view** or **torch.reshape** to flatten a specific dimension, we will have to remove the dimension that is not used (the one it is empty): 

In [20]:
z1 = y2.squeeze(0)
print(z1, z1.size())

tensor([[ 1.,  2.],
        [ 3.,  4.],
        [ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.],
        [11., 12.]]) torch.Size([6, 2])


If you try to remove a dimension that is not empty it will do nothing: 

In [21]:
z2 = y2.squeeze(1)
print(z2, z2.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]) torch.Size([1, 6, 2])


You can also create a new dimenion (empty of course) by using the opposite function **torch.unsqeeze**

In [22]:
z3 = z1.unsqueeze(0)
print(z3, z3.size())

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]]) torch.Size([1, 6, 2])


## Function 5 - torch.argmax vs torch.max

**torch.argmax** returns the indices of the maximum value of all elements in the input tensor.

In [26]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.]],

        [[ 7.,  8.],
         [ 9., 10.],
         [11., 12.]]])

In [27]:
x.argmax(dim=1)

tensor([[2, 2],
        [2, 2]])

**torch.max** returns also the maximum values:

In [28]:
x.max(dim=1)

torch.return_types.max(values=tensor([[ 5.,  6.],
        [11., 12.]]), indices=tensor([[2, 2],
        [2, 2]]))

You can do the same using both functions but with 1D tensor. 

In [32]:
y = x.flatten()
print(y.argmax(), y.max(dim=0))

tensor(11) torch.return_types.max(
values=tensor(12.),
indices=tensor(11))


## Conclusion

Here we mentioned some functions that might be used to prepare the input given to the model or when the output of the model needs to be changed to fit in the loss function for instance. It is really important to understand how these functions change the data regarding dimensions and shape, and also how to interpret their ouptut. 

## Reference Links
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html